spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/studentmanager?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb

mybatis:
  # 实体类
  type-aliases-package: com.czx.myownstumanager.pojo
  # 指定mybatis的核心配置文件与Mapper映射文件
  mapper-locations: classpath:mapper/*.xml